// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD438tXmbsk0RxCubSziGC-87y648bPc_U',
    appId: '1:584591285878:web:ffb3194b49b0f92c868957',
    messagingSenderId: '584591285878',
    projectId: 'fitnessapp-77f40',
    authDomain: 'fitnessapp-77f40.firebaseapp.com',
    storageBucket: 'fitnessapp-77f40.firebasestorage.app',
    measurementId: 'G-0G0FDCH3SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeuA8ZbWUe1UVn78vb579Xp9R_bn03Xv8',
    appId: '1:584591285878:android:f6b9b30825361d09868957',
    messagingSenderId: '584591285878',
    projectId: 'fitnessapp-77f40',
    storageBucket: 'fitnessapp-77f40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsNNlsd8rxQReVFkRKCU8d7Io2ralUgYk',
    appId: '1:584591285878:ios:c94fddb8e999572a868957',
    messagingSenderId: '584591285878',
    projectId: 'fitnessapp-77f40',
    storageBucket: 'fitnessapp-77f40.firebasestorage.app',
    iosBundleId: 'com.example.fitnessapp',
  );

}