name: fitnessapp
description: "A comprehensive fitness companion for tracking nutrition, workouts, and health metrics to help users achieve their fitness goals."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.2.1
  intl: ^0.18.1
  logger: ^2.0.2
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  animated_splash_screen: ^1.3.0
  firebase_core: ^3.14.0
  gender_picker: ^1.1.0
  step_progress_indicator: ^1.0.2
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gym1.png
    - assets/splashscreen.gif
    - assets/2nd page.png
    - assets/try2.png
    - assets/girlboy.png
    - assets/logo.png
    - assets/logo2.png
    - assets/girl.png
    - assets/img.png
    - assets/Frame_eat.png
    - assets/AgeGenderImages/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 800  # Changed from 800 (standard weights are 100-900 in increments of 100)
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins-Light.ttf
          weight: 300