name: fitnessapp
description: "A comprehensive fitness companion for tracking nutrition, workouts, and health metrics to help users achieve their fitness goals."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  gender_picker: ^1.1.0
  step_progress_indicator: ^1.0.2
  numberpicker: ^2.1.2
  simple_ruler_picker: ^0.1.1
  flutter_ruler_picker: ^1.0.6
  provider: ^6.1.5
  firebase_auth: ^5.6.0
  shared_preferences: ^2.5.3
  iconsax: ^0.0.8
  percentages_with_animation: ^1.1.1
  openfoodfacts: ^3.23.0
  http: ^1.4.0
  crypto: ^3.0.0



  # Add other dependencies here with proper indentation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:

    - assets/
    - assets/AgeGenderImages/
    - assets/GoalSelectionImg/
    - assets/ActivityLevel/
    # Add other assets here

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700